name: Auto Assign Issues

on:
  issues:
    types: [opened]
  workflow_dispatch: # Allow manual trigger

permissions:
  issues: write

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
    - name: Get Issue URL
      run: |
        echo "The issue URL is: ${{ github.event.issue.html_url }}"
